name: inflection
version: 0.2.0
author: George Moschovitis <george.moschovitis@gmail.com>
description: A port of Rails' ActiveSupport inflection library to Dart.
homepage: https://github.com/gmosx/dart-inflection
dev_dependencies:
  unittest: any
